[package]
name = "complex"
version = "0.1.0"
authors = ["ddorn <diego.dorn@free.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.2.0"
image = "0.22.2"